// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC9EnATRzjujuxOIGPeiFW-dabHbbozE8',
    appId: '1:94825369955:web:7187e845b46cd7be2f8356',
    messagingSenderId: '94825369955',
    projectId: 'farm-easy-hackathon',
    authDomain: 'farm-easy-hackathon.firebaseapp.com',
    storageBucket: 'farm-easy-hackathon.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Km7e9AE3eY9CTaHOiC5VXORbseZtneU',
    appId: '1:94825369955:android:e8ed5b2249db13ca2f8356',
    messagingSenderId: '94825369955',
    projectId: 'farm-easy-hackathon',
    storageBucket: 'farm-easy-hackathon.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwNMCAvIzmfedOBN-Lryams0ZVGNemnIw',
    appId: '1:94825369955:ios:8e82fe3cddccda6e2f8356',
    messagingSenderId: '94825369955',
    projectId: 'farm-easy-hackathon',
    storageBucket: 'farm-easy-hackathon.appspot.com',
    iosClientId: '94825369955-rb3ldv4dabfs1dh8fma7p29niim4bk3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmeasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwNMCAvIzmfedOBN-Lryams0ZVGNemnIw',
    appId: '1:94825369955:ios:8e82fe3cddccda6e2f8356',
    messagingSenderId: '94825369955',
    projectId: 'farm-easy-hackathon',
    storageBucket: 'farm-easy-hackathon.appspot.com',
    iosClientId: '94825369955-rb3ldv4dabfs1dh8fma7p29niim4bk3h.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmeasy',
  );
}
